## NumPy数组的优势

NumPy数组通常是由相同种类的元素组成的，既数组中的数据项的类型必须一致。



In [2]:
import numpy as np

In [6]:
a = np.arange(5)
# a.dtype
#a.dtype
a.dtype
a.shape

(5L,)

以上数组的数据类型为int32，除了知道数据类型之外，还要注意其形状，这一点非常重要

In [11]:
a.shape
np.ones(20)
np.eye(5)
np.arange(0, 100, 5) 
np.random.randn(5,5)

array([[-0.10445168,  0.7774044 ,  0.13187735, -0.24417755,  1.41799676],
       [-1.97151801,  0.83457858,  0.74749306, -0.58529186, -0.02607808],
       [ 0.05240936,  0.13454641,  1.28879802, -2.43908872, -0.72733447],
       [ 0.01645803, -2.81641124, -0.09518419, -0.58709535,  0.4804176 ],
       [-1.70224265,  2.027883  ,  0.04817628,  0.13818806, -0.50162259]])

In [14]:
#创建NumPy数组
np.array([2, 3, 4])
np.zeros(20)
np.ones((3,3,3), dtype=np.int32)
np.eye(5)
np.arange(0, 100, 5) 
np.random.randn(5,5,5).ndim

3

我们已经知道了创建的方法，下面查看numpy数组的一些属性

In [15]:
array = np.array([[1,2,3],[2,3,4]])
print(array)
print('number of dim:',array.ndim) #矩阵的维度
print('shape:',array.shape) # 矩阵的大小
print('size:',array.size) #矩阵的元素个数

[[1 2 3]
 [2 3 4]]
('number of dim:', 2)
('shape:', (2L, 3L))
('size:', 6)


## 选择NumPy数组元素

In [36]:
a = np.arange(100)
a
a[0:3]
a[10:20]
a[40:]
a[-1]
# # a
# #如何倒序
Z = np.arange(50)
Z = Z[::-1]
#print(Z)
np.nonzero([1,2,0,0,4,0])
c= np.random.random((10))
print c
c.min()
np.argmax(c)
c.mean()
np.median(c)
np.var(c)
np.diff(c)

[ 0.0142107   0.51231133  0.03531172  0.00629702  0.66707791  0.81120638
  0.64854311  0.83643131  0.7363546   0.50351455]


array([ 0.49810063, -0.47699961, -0.0290147 ,  0.66078089,  0.14412846,
       -0.16266326,  0.1878882 , -0.10007671, -0.23284005])

# numpy 函数

In [40]:
# np.nonzero([1,2,0,0,4,0])
# c= np.random.random((10))
# print c
# cmin, cmax = c.min(), c.max()
# print(cmin, cmax)
# # # #argmin返回是c数组中最小元素的索引值，argmax返回最大值索引值
# np.argmin(c)
# np.argmax(c)

# # # #算术平均
# np.mean(c)
# # # #取值范围
# np.max(c)
# np.min(c)
# # #ptp函数返回最大值与最小值之间的差值
# np.ptp(c)
# # #median函数返回中位数
# np.median(c)
# # #var方差
# np.var(c)
# # #diff函数返回一个由相邻数组元素的差值构成的数组
# np.diff(c)
# #prod计算数组中所有元素的乘积
b = np.arange(1, 9)
b
b.prod()
# #cumprod方法，计算数组元素的累积乘积
b.cumprod()


array([    1,     2,     6,    24,   120,   720,  5040, 40320])

## 处理数组形态

In [42]:
b = np.arange(24).reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [43]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [44]:
b.resize((2,12))
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

转置：在线性代数中，矩阵的转置操作非常常见。转置是一种数据变换方法，对于二维表而言，转置就意味着行变成列，同时列变成行。转置也可以通过下列代码完成：

In [45]:
b.transpose()

array([[ 0, 12],
       [ 1, 13],
       [ 2, 14],
       [ 3, 15],
       [ 4, 16],
       [ 5, 17],
       [ 6, 18],
       [ 7, 19],
       [ 8, 20],
       [ 9, 21],
       [10, 22],
       [11, 23]])

### 堆叠数组
从深度看，数组既可以横向叠放，也可以竖向叠放，为此，可以使用vstack()、dstack()、hstack()、column_stack()、row_stack()和concatenate()等函数。


In [46]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
b= 2*a
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

水平叠加：先介绍水平叠加方式，即用元组确定ndarrays数组的形状，然后交由hstack（）函数来码放这些数组。

In [48]:
np.hstack((a,b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

用concatenate（）函数也能达到相同的效果。

In [49]:
np.concatenate((a,b),axis = 1)
#0：作用对象是index； 1：作用对象是columns。

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

垂直叠加：使用垂直叠加方法时，先要构建一个元祖，然后将元祖交给vstack（）函数来码放数组。

In [52]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

当参数axis置0时，concatenate（）函数也会得到相同的效果。实际上，这是该参数的缺省值：

In [54]:
np.concatenate((a,b),axis = 0)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

深度叠加：除此之外，还有一种深度叠加方法，这要用到dstack（）函数和一个元组。这种方法是沿着第三个坐标轴（纵向）的方向来叠加一摞数组。举例来说，可以在一个图像数据的二维数组上叠加另一幅图像的数据。

In [30]:
np.dstack((a,b))

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

列式堆叠：columns_stack()函数以列方式对一维数组进行堆叠。

### 拆分NumPy数组
可以从纵向，横向和深度方向来拆分数组，相关函数有hsplit(),vsplit(),dsplit()和split()。我们即可以把数组分成相同的形状的数组，也可以从规定的位置开始切取数组。

横向拆分：对于一个3行3列数组，可以沿着横轴方向将其分解为3部分，并且各部分的大小和形状完全一致。

In [55]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
np.hsplit(a,3)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

这个相当于调用了参数axis = 1的split（）函数：

In [56]:
np.split(a,3,axis = 1)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

纵向拆分：同理

In [59]:
np.vsplit(a,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [58]:
np.split(a,3,axis = 0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

深向拆分：dsplit()函数会沿着深度方向分解数组。下面以秩为3的数组为例进行说明：